bench:
    - tpcc
graph:
    using_cmd: ($6):($7)
    log_scale: xy 10
    x_label: 'Clients'
    y_label: 'Throughput (txn/s)'
    y_range: '[1:]'
    x_range: '[1:4000]'
    output_file: 'single_dc_${bench}_${txn}_client_tp_log'
    key_location: 'above'
    y_format: '"10^%T"'