
bench:
  workload: tpca
  scale: 1
  weight:
    read: 0
    write: 1
  population: # intial number of records in each table
    branch:   1000000
    teller:   1000000
    customer: 1000000
  dist: zipf
  coefficient: 0.0 # 0 as unifrom, 1 as pure zipf

schema:
  - name: branch
    column:
      - {name: branch_id,   type: integer, primary: true} 
      - {name: balance,     type: integer} 
  - name: teller
    column:
      - {name: teller_id,   type: integer, primary: true}
        #- {name: branch_id,   type: integer, foreign: branch.branch_id }
      - {name: balance,     type: integer} 
  - name: customer
    column:
      - {name: customer_id, type: integer, primary: true}
        #      - {name: branch_id,   type: integer, foreign: branch.branch_id}
      - {name: balance,     type: integer}

sharding:
  teller:   MOD
  branch:   MOD
  customer: MOD
