
bench:
  workload: tpca
  scale: 1
  weight:
    read: 0
    write: 1
  population: # intial number of records in each table
    branch:   100000
    teller:   100000
    customer: 100000
  dist: uniform 
  coefficient: 1 # 0 as unifrom, 1 as pure zipf

schema:
  - name: branch
    column:
      - {name: branch_id,   type: integer, primary: true} 
      - {name: balance,     type: integer} 
  - name: teller
    column:
      - {name: teller_id,   type: integer, primary: true}
        #      - {name: branch_id,   type: integer, foreign: branch.branch_id }
      - {name: balance,     type: integer} 
  - name: customer
    column:
      - {name: customer_id, type: integer, primary: true}
        #      - {name: branch_id,   type: integer, foreign: branch.branch_id}
      - {name: balance,     type: integer}

sharding:
  teller:   MOD
  branch:   MOD
  customer: MOD
